dzm_site/dzm_site/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('landing.urls')),
    url(r'', include('orders.urls')),
    url(r'', include('products.urls')),

] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dzm_site/orders/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^basket_adding/$', views.basket_adding, name='basket_adding'),
    url(r'^checkout/$', views.checkout, name='checkout'),
]

dzm_site/products/urls.py
from django.conf.urls import url

from products.views import product_view


urlpatterns = [
    url(r'^product/(?P<product_id>\w+)/$', product_view, name='product'),
    ]

dzm_site/products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return f'{self.name}'


    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категория товаров'


class Product(models.Model):
    name = models.CharField(max_length=128, blank=True, null=True, default=None)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, blank=True, null=True, default=None)
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)


    def __str__(self):
        return '%s:%s' % (self.id, self.name)


    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class ImageProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)


    def __str__(self):
        return f'{self.id} {self.product.name}'


    class Meta:
        verbose_name = 'Image of product'
        verbose_name_plural = 'Images of products'


# Create your models here.

dzm_site/products/views.py
from django.shortcuts import render
from .models import Product


# Create your views here.

def product_view(request, product_id):

    print("______products.views.py___________def product_view____________")
    this_product = Product.objects.get(id=product_id)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print(f'session_key: {request.session.session_key}')
    print(f'request_get {request.GET}')
    print(f'request_post {request.POST}')


    return render(request, 'products/product.html', locals())

dzm_site/templates/products/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for item_prod in this_product.imageproduct_set.all %}
                    <div class="product-image-item">
                        <img src="{{ item_prod.image.url }}" class="img-responsive" style="width:100%">
                    </div>

                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ this_product.name }}
                </h1>

                <div class="">
                    <p>
                        Цена: {{ this_product.price }} руб.
                    </p>
                </div>

                <div>
                    <nav>
                      <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="description-tab" data-toggle="tab" href="#nav-descr" role="tab" aria-controls="nav-descr" aria-selected="true">
                            Описание
                        </a>
                        <a class="nav-item nav-link" id="delivery-tab" data-toggle="tab" href="#nav-delivery" role="tab" aria-controls="nav-profile" aria-selected="false">
                            Доставка
                        </a>
                        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">
                            Contact
                        </a>
                      </div>
                    </nav>
                    <div class="tab-content tab-description" id="nav-tabContent">
                      <div class="tab-pane fade show active" id="nav-descr" role="tabpanel" aria-labelledby="nav-home-tab">
                          {{this_product.description}}
                          <form id="form_buying_product" class="form-inline" action="{% url 'basket_adding' %}"> {% csrf_token %}
                              <div class = "form-group">
                                  <input type="number" class="form-control" id="number" style="margin-top:10px">
                                  <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                    data-product_id="{{this_product.id}}"
                                    data-product_name="{{this_product.name}}"
                                    data-product_price="{{this_product.price}}"
                                  >
                                      Купить
                                  </button>
                              </div>
                          </form>

                      </div>
                      <div class="tab-pane fade" id="nav-delivery" role="tabpanel" aria-labelledby="delivery-tab">Мы доствим Ваш товар в любую точку мира</div>
                      <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">asdfssdsfsd</div>
                    </div>
                </div>




            </div>
        </div>
    </div>
{% endblock %}